### ISSUE TITLE
How to override the default close icon?

### ISSUE THREAD

**Issue by chamnap** [ifad/data-confirm-modal#42]
I would like to override the default close icon to use google material icon `<i class='material-icons'>clear</i>`. Is there any callbacks before the modal is shown so that I could inject the above html code. Or do you have any suggestions to do so?

Appreciate your response!

**Comment by lucaspiller** [comment]
Hi @chamnap. Unfortunately there isn't a way to override it. We are using the [standard Bootstrap close icon](http://getbootstrap.com/css/#helper-classes-close). You might be able to use CSS to change it with some `content` and `after` trickery. Otherwise feel free to send a PR to allow it be changed!

**Comment by milianriedel** [comment]
@chamnap Merged in https://github.com/ifad/data-confirm-modal/pull/69
