### ISSUE TITLE
Changing confirmation text only works once

### ISSUE THREAD

**Issue by marat-y** [ifad/data-confirm-modal#66]
Hello!

I'm trying to dynamically change confirmation text. But dialog actually changes only the first time I change data-confirm value. Is there anything else I'm doing wrong or some event I need to trigger for this to work correctly?

I'm using v.1.3.0.

UPD. Updating to 1.6.1 made no effect.

**Comment by vjt** [comment]
Hi, sorry for the late reply.

When using [`data-` attributes](https://github.com/ifad/data-confirm-modal/#with-rails-example-b3-example-b4), the modal is built once by [buildModal](https://github.com/ifad/data-confirm-modal/blob/master/vendor/assets/javascripts/data-confirm-modal.js#L117) and then cached into the `confirm-modal` data attribute by [getConfirmModal](https://github.com/ifad/data-confirm-modal/blob/master/vendor/assets/javascripts/data-confirm-modal.js#L286).

If you want to keep using `data-` attributes, you can use the newly exposed `.getConfirmModal()` to get the modal object, and then:

```js
$(..).getConfirmModal().find('.modal-body p').text('new text')
```

Otherwise, you can use the [`window.dataConfirmModal()` API](https://github.com/ifad/data-confirm-modal/#without-rails-without-data-attributes-example-b3-example-b4), that creates new modals every time it is called.

**Comment by JamesPlayer** [comment]
Hi, it looks like `$(..).getConfirmModal()` is not in the latest release (v1.6.2). Could you please release it when you get a chance?

**Comment by vjt** [comment]
Hi @JamesPlayer,

`1.6.3` has been pushed to rubygems. Thanks for the heads up.

**Comment by jamgregory** [comment]
@vjt - please could you push the latest version to npmjs? It doesn't look like it has been updated there. Thanks! :+1:

**Comment by Halloran** [comment]
same here...
